# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022 Osyris contributors (https://github.com/osyris-project/osyris)

name: Build Osyris

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
    - name: Install dependencies
      run: |
        which python
        python -m pip install --upgrade pip
        python -m pip install flake8==7.0.0 toml black[jupyter]==24.3.0 build pytest==7.4.2
    - name: Check black formatting
      run: |
        black --check .
    - name: Lint with flake8
      run: |
        flake8 . --count --statistics
    - name: Run python tests
      run: |
        pip install -r docs/requirements.txt
        python -m pip install -e .
        python -m pytest test
    - name: Build documentation
      run: |
        sudo apt install pandoc
        sphinx-build -j2 -b html docs/. docs/build
    - name: Archive documentation artifacts
      uses: actions/upload-artifact@v4
      with:
        name: DocumentationHTML
        path: docs/build
    - name: Build a binary wheel and a source tarball
      if: startsWith(github.ref, 'refs/tags')
      run: |
        python -m build --sdist --wheel --outdir dist/ .
    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@v1.8.10
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
